### PR TITLE
CSS: Made buttons look more like Web 2.0 buttons

### PR DESCRIPTION
**Pull request by RobertAKARobin**

### CODE REVIEW

**Comment by RobertAKARobin** [comment]
@mattscilipoti How's this?

**Comment by adambray** [comment]
This is even nicer IMO... that said, maybe make delete buttons red?

**Comment by RobertAKARobin** [comment]
Hah, I feel like we're basically reinventing Bootstrap.

**Comment by mattscilipoti** [comment]
Reinventing?  Maybe.  At least the button portion.  There's only so much we can do with buttons and have them still be, obviously, buttons.  I certainly wasn't trying to stunt your creativity.  If you really want the rounded, shadowed buttons, I won't fight it. Now that I see it, I definitely prefer the shorter buttons though.

**Comment by RobertAKARobin** [comment]
@adambray @mattscilipoti I added styling for delete buttons!

**Comment by adambray** [comment]
Roger Ebert gives this pull request "Two Thumbs Up".

**Comment by RobertAKARobin** [comment]
I'm mergin'!

**Pull request merged**
