### PR TITLE
remove orphans link

### PR DESCRIPTION
**Pull request by jshawl**

### CODE REVIEW

**Comment by andrewsunglaekim** [comment]
was orphans a problem before? and why are they not now? is this something we're going to clean up in a different way going forward?

**Comment by RobertAKARobin** [comment]
Orphans were users who had no memberships. I'm unsure whether this is still a problem.

**Comment by adambray** [comment]
I don't think it's a problem, and would vote to remove this (i.e. merge this PR)

:+1:

**Comment by RobertAKARobin** [comment]
:+1:

**Pull request merged**
