### PR TITLE
fixes #524

### LINKED ISSUE #524: % present missing from users show page

### PR DESCRIPTION
**Pull request by jshawl**

### CODE REVIEW

**Comment by RobertAKARobin** [comment]
Thumb sideways. This means we can't sort by tardy anymore.

**Comment by adambray** [comment]
I'm not a fan of this. To me knowing the spread of tardies vs absences is far more important.

**Comment by adambray** [comment]
Also, these numbers are necessary to determine graduation status (given the formula for tardies -> absences).

**Comment by jshawl** [comment]
Student is requesting % present. Should I tell them no on that feature?

**Comment by RobertAKARobin** [comment]
Maybe let's just have % present instead of % absent

**Comment by adambray** [comment]
porque no los tres? (mostly jk)

Why do they want it? That's the important question to me.

-Adam

**Comment by RobertAKARobin** [comment]
See https://github.com/ga-dc/garnet/pull/530

**Pull request closed without merging**
