### PR TITLE
removed default values for submissions and attendances so can be nil

### PR DESCRIPTION
**Pull request by RobertAKARobin**

### CODE REVIEW

**Comment by RobertAKARobin** [comment]
This allows us to show that an attendance/submission has *not* been taken. Currently, they default to "absent" by default, which makes it difficult to see which absences are "real".

**Comment by jshawl** [comment]
:+1: waiting for today's attendance to be taken before merge

**Comment by RobertAKARobin** [comment]
It shouldn't affect it, but good call.

**Comment by jshawl** [comment]
i feel similarly! just in case...

**Pull request merged**
