### PR TITLE
uses see_observations check to manage view for avg obz

### PR DESCRIPTION
**Pull request by nolds9**

### CODE REVIEW

**Comment by jshawl** [comment]
:+1:

**Comment by adambray** [comment]
This is better, but the caching call needs to be updated.

**Comment by nolds9** [comment]
@adambray could you elaborate on what need to be updated on the caching end?

**Comment by adambray** [comment]
Ready for review

**Comment by nolds9** [comment]
sorry Adam, didn't see your commit. :+1:  for me!

**Comment by RobertAKARobin** [comment]
:+1:

**Pull request merged**
