### PR TITLE
remove pending tests

### PR DESCRIPTION
**Pull request by jshawl**

### CODE REVIEW

**Comment by RobertAKARobin** [comment]
:+1:

**Comment by nolds9** [comment]
:+1:

**Comment by andrewsunglaekim** [comment]
i think i had tried to remove some of these in a prior PR, but Adam recommended against it. As it kind of acts like a todo for testing? I dunno, would like adam's thoughts on this PR. @adambray

**Comment by adambray** [comment]
@jshawl @andrewsunglaekim the more I look at these, the more I'm ok with removing them. A lot has changed, and most of the group stuff isn't relevant anymore.

Probably favor starting with acceptance testing most things, and doing so from scratch (excluding existing acceptance tests that work).

**Pull request merged**
