### PR TITLE
nest assignments under cohort

### PR DESCRIPTION
**Pull request by jshawl**
easier to move back wip please comment

### CODE REVIEW

**Comment by adambray** [comment]
@jshawl could you clarify the reasoning behind this? I'm totally down with it technically, just want to understand the why!

**Comment by jshawl** [comment]
navigability via the url

**Comment by adambray** [comment]
Do we need to navigate by URL? If that's the only reason, could we improve the UX / views to support easier navigation?

**Comment by jshawl** [comment]
closing - stale

**Pull request closed without merging**
