### PR TITLE
Tidying up the stylesheets

### PR DESCRIPTION
**Pull request by RobertAKARobin**
- Doesn't change any CSS; just separates it out into different stylesheets for better manageability

### CODE REVIEW

**Comment by RobertAKARobin** [comment]
Tested with minified assets; appears to work just fine.

**Comment by RobertAKARobin** [comment]
This is in anticipation of doing a CSS overhaul because, no disrespeck, Garnet's looking a little gnarly.

**Comment by jshawl** [comment]
:+1:

**Comment by adambray** [comment]
Hell yeah!

Also, I feel like there's a pun about Garnet and gnarly... Garnly? Hmmm, never mind. I'll see myself out.

**Comment by adambray** [comment]
@jshawl @RobertAKARobin while we're talking about CSS, what are your thoughts re eventually structuring the CSS like it's done here:

https://github.com/YaleSTC/reservations/tree/master/app/assets/stylesheets

By that, I don't mean using bootstrap, but rather more SASS, `@import`, a variables file, etc?

**Comment by adambray** [comment]
(Not sure it's the right move, asking because I want to hear thoughts from those more enlightened / practiced with big CSS codebases)

**Comment by RobertAKARobin** [comment]
Totally into it! I just don't really know SASS that well and so kicked it old school. Maybe that'll be my next PR. Can I merge?

**Pull request merged**
