### PR TITLE
Event: rename column “date” to “occurred_at”

### PR DESCRIPTION
**Pull request by mattscilipoti**
- avoiding reserved words
- matches existing pattern: created/updated_at
- occurred_at should be *much* easier to search for. :)
- e.g. `if event.occurred_at.today?`.  Winner!

### CODE REVIEW

**Comment by adambray** [comment]
TBH, I'm down with this, as it's a notable improvement, but I wonder if there isn't an even better name, since events can occur in the future? 

What about `occurs_on`?

**Comment by adambray** [comment]
Also, thanks for making a PR that's strictly code cleanup!!!

**Comment by mattscilipoti** [comment]
I feel occurred_on/occurs_on would indicate a date, not a datetime.

**Comment by mattscilipoti** [comment]
The event occurred on Tuesday.  I agree, the "at" is a bit concise.  The occurred on Tuesday, at 2:00pm.  I could go with occurs_at.  Since it may be in the future.

**Comment by mattscilipoti** [comment]
Making the change.

**Comment by mattscilipoti** [comment]
@adambray Renamed to occurs_at.

**Comment by adambray** [comment]
:+1:

**Comment by andrewsunglaekim** [comment]
:+1:

**Pull request merged**
