### PR TITLE
Group show page contains attendance, assignments, etc; one-click grading

### PR DESCRIPTION
**Pull request by RobertAKARobin**

### CODE REVIEW

**Comment by jshawl** [comment]
17 files changed!

**Comment by RobertAKARobin** [comment]
Yup. It's because I'm basically consolidating all of the views into just a few:

```
sign up
sign in
user show
group show
take attendance for event
grade submissions for assignment
```

**Comment by RobertAKARobin** [comment]
The failures are just because of date formatting

**Comment by jshawl** [comment]
new or old error?

**Comment by RobertAKARobin** [comment]
Working on those now. New error because I removed the partial

**Comment by RobertAKARobin** [comment]
Everything should work now. Next step is adding back the "percent complete" etc. on the group show page. Where's Travis?

**Comment by RobertAKARobin** [comment]
Split into multiple commits

**Comment by RobertAKARobin** [comment]
Obviously there's a boatload of a stuff in here, but it's all focused on reorganizing the views/grading system, and all builds on each other to that end -- there isn't really anything unrelated to that. I hope we can pair soon so I can show it to you!

**Comment by RobertAKARobin** [comment]
Obviously there's a boatload of a stuff in here. It's all focused on reorganizing the views/grading system. There's not really anything unrelated to that, which is why I thought it was appropriate to have it in one PR (but multiple commits) in the interest of being able to add this specific functionality to production sooner rather than later. I hope we can pair soon so I can show it to you!

**Pull request closed without merging**
