### PR TITLE
Revamping css

### PR DESCRIPTION
**Pull request by RobertAKARobin**

### CODE REVIEW

**Comment by adambray** [comment]
@RobertAKARobin I like it, though I'm definitely gonna miss the old garnet look and feel.

A few issues:

1. Headers for cohort show page seem small.
2. Status buttons (for taking attendance / grading) need color differentiation between selected and unselected
3. Style for forms for events, hw, are a bit wonky. (size and dashed borders on inputs)

**Comment by adambray** [comment]
"that looks great. Just one thing - get rid of the duck."

[check out number 5](http://blog.codinghorror.com/new-programming-jargon/)

**Comment by RobertAKARobin** [comment]
THE DUCK STAYS OR I GO.

**Comment by adambray** [comment]
Too late, you're :fire: 'd

**Comment by adambray** [comment]
slack-imgs com

**Pull request merged**
