### PR TITLE
fix user, location and course associations

### PR DESCRIPTION
**Pull request by amaseda**

### CODE REVIEW

**Comment by adambray** [comment]
@amaseda looks like you need to check that schema.rb was committed properly... the tests are failing because `schema.rb` doesn't match the migrations.

**Comment by nolds9** [comment]
:+1:

**Comment by jshawl** [comment]
travis failure: https://travis-ci.org/ga-dc/garnet/builds/105686293#L318

**Comment by adambray** [comment]
:+1:

**Pull request merged**
