### PR TITLE
Added custom table sorting JS library

### PR DESCRIPTION
**Pull request by RobertAKARobin**
- Sorting
  - Not limited to tables: can be used for any series of records
  - Also includes filtering, both by typing input and clicking "trigger" elements (e.g. tags)
  - Angular-ish HTML attribute-based system
  - Updated all tables to match
  - Works with `colspan` and `rowspan`, unlike `jsDataTables`
- Also moved tag_list to its own partial view

- Fixes https://github.com/ga-dc/garnet/issues/519
- Fixes https://github.com/ga-dc/garnet/issues/515

### CODE REVIEW

**Comment by adambray** [comment]
@RobertAKARobin overall, I really like this! I'm giving it my :+1: pending a bit more testing I'd like to do tomorrow morning.

Only one thought... how hard would it be to make it so we don't have to specify `data-sort-trigger="foo"` and `data-sort-field="foo"`? I.e. to just place a `data-sort-trigger` on the header, and if no value is specified, to just sort by that column (while still supporting the current behavior of letting you specify the field if need be.

**Comment by RobertAKARobin** [comment]
I think it'd require writing a lot more code: you'd need to count the index of that particular header, find the matching cell, and *then* start to consider `colspan`. That's the approach I tried a couple times before settling on this.

**Comment by RobertAKARobin** [comment]
Thanks for reviewing!

**Comment by adambray** [comment]
:+1: 

I'm ok with merging this in as long as we create an issue for the multi-column sort (it can be a low priority one).

**Comment by jshawl** [comment]
:+1: pending issue creation and merge conflict resolution. good to merge!

**Pull request merged**
