### PR TITLE
Cancan authorization and tests; Shows grades due in instructors' user profiles

### PR DESCRIPTION
**Pull request by RobertAKARobin**

### CODE REVIEW

**Comment by RobertAKARobin** [comment]
TODO: Ask how to put things in different pull requests when they all kinda build off each other.

**Comment by RobertAKARobin** [comment]
Then again, maybe I won't. !@#$% computer.

**Comment by jshawl** [comment]
:+1: will merge. pending ability to add is_priority status for members

**Comment by jshawl** [comment]
via the gui

**Comment by RobertAKARobin** [comment]
@jshawl Ready to rock

**Pull request merged**
