### PR TITLE
add custom favicon

### PR DESCRIPTION
**Pull request by ebirving**

### CODE REVIEW

**Comment by RobertAKARobin** [comment]
For some bizarre reason, Travis doesn't like it when you make a PR from another repo. Instead, try pushing to a branch on this repo, and making a pull request from that.

**Comment by RobertAKARobin** [comment]
(Hence why this repo has 23 branches, and counting.)

**Comment by ebirving** [comment]
Ah! Thank you!

**Comment by RobertAKARobin** [comment]
(Hence why this repo has 23 branches, and counting.)

**Pull request closed without merging**
