### PR TITLE
Issue#593 Updates observation_average when observation is deleted

### PR DESCRIPTION
**Pull request by awhit012**

### CODE REVIEW

**Comment by awhit012** [comment]
When I went back and wrote a test, it forced me to rethink it and I rewrote the solution. Another reason why testing is great. :)

**Comment by nolds9** [comment]
👍  & tests!

**Comment by awhit012** [comment]
Yeah I submitted earlier without the test, and Adam asked if I would write a test for it. Went back to write the test and that made me figure out a better way to solve the issue! That made me pretty happy.

**Comment by amaseda** [comment]
:+1:

**Pull request merged**
